#! /bin/bash
file=$HOME/full.log
i=""
w=""
logfile="/var/log/Xorg.0.log"
while read -r line; do
	if [[ $line =~ (II) ]]; then
		i+="${line}\n"
	fi
	if [[ $line =~ (WW) ]]; then
		w+="${line}\n"
	fi
done < "$logfile"
i=$(echo $i | sed 's/(II)/Information:/g')
w=$(echo $w | sed 's/(WW)/Warning:/g')
echo -e $i >> $file
echo -e $w >> $file
exit 0
