#!/bin/bash
~/lab6/seven_handler&
while true
do
	read line
	case "$line" in
	"T")
		kill -SIGTERM $(cat seven_operation)
		exit 0
		;;
	"+")
		kill -USR1 $(cat seven_operation)
		;;
	"*")
		kill -USR2 $(cat seven_operation)
		;;
	*)
		continue
		;;
	esac
done
exit 0
