#!/bin/bash
date=$(ls $HOME | grep -E "^Backup-" | sort -n | tail -1 | cut -d "-" -f 2,3,4)
[ -z $date ] && echo "Backup-yyyy-MM-dd: Not such file or directory" && exit 1
[ -d $HOME/restore ] && rm -r $HOME/restore
mkdir $HOME/restore
bkpFiles=$(ls $HOME/Backup-$date)
for file in $bkpFiles
do
	fileDate=$(echo $file | grep -a -o -E '[A-Za-z0-9]+\-[0-9]{4}\-[0-9]{2}\-[0-9]{2}' |
	grep -a -o -E '[0-9]{4}\-[0-9]{2}\-[0-9]{2}')
	[ -z $fileDate ] && cp -r $HOME/Backup-$date/$file $HOME/restore
done
exit 0
